export interface ClosedJobRecord {
  id: string;
  raw_message: string;
  company_id: string;
  whatsapp_group_id: string;
  company_name: string;
  customer_name: string;
  phone: string;
  address: string;
  service: string;
  appointment: string;
  technician_name: string;
  closed_amount: number;
  payment_method: string;
  created_at: Date;
  source_message_id: string;
  needs_review: boolean;
}

/**
 * Input type for saving a new job.
 * `id` and `created_at` are generated by the repository — callers do not supply them.
 */
export type NewClosedJob = Omit<ClosedJobRecord, "id" | "created_at">;

export type SaveResult =
  | { ok: true; record: ClosedJobRecord }
  | { ok: false; error: "DUPLICATE_SOURCE_MESSAGE_ID" };
